### ISSUE TITLE
Changes todo in the draft

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Ramses-Client#1]
# move dbi calls into classes

- [ ] Add a "suspend" option in DBInterface to temporarily suspend calls when getting updates from the db.

- [ ] Move createUser in RamUser constructor

- [ ] Move removeUser in RamUser destructor

# RamUser

- [ ] Change password without specifying current one (when set by admin) (and add necessary dbi call)

# Server

- [ ] check if user is admin/lead/standard, and keep uuid, for further checks when modifying things
